// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/proto/comfy.proto

package mea_gen_d

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Comfy_SetImage_FullMethodName    = "/meagen.Comfy/SetImage"
	Comfy_SetPrompt_FullMethodName   = "/meagen.Comfy/SetPrompt"
	Comfy_SetMask_FullMethodName     = "/meagen.Comfy/SetMask"
	Comfy_SetOptions_FullMethodName  = "/meagen.Comfy/SetOptions"
	Comfy_SetCrop_FullMethodName     = "/meagen.Comfy/SetCrop"
	Comfy_Inpaint_FullMethodName     = "/meagen.Comfy/Inpaint"
	Comfy_UberInpaint_FullMethodName = "/meagen.Comfy/UberInpaint"
	Comfy_Img2Img_FullMethodName     = "/meagen.Comfy/Img2Img"
	Comfy_Txt2Img_FullMethodName     = "/meagen.Comfy/Txt2Img"
	Comfy_Ipnet_FullMethodName       = "/meagen.Comfy/Ipnet"
	Comfy_Reboot_FullMethodName      = "/meagen.Comfy/Reboot"
)

// ComfyClient is the client API for Comfy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComfyClient interface {
	SetImage(ctx context.Context, in *SlotedImage, opts ...grpc.CallOption) (*Empty, error)
	SetPrompt(ctx context.Context, in *SlotedPrompt, opts ...grpc.CallOption) (*Empty, error)
	SetMask(ctx context.Context, in *Image, opts ...grpc.CallOption) (*Empty, error)
	SetOptions(ctx context.Context, in *Options, opts ...grpc.CallOption) (*Empty, error)
	SetCrop(ctx context.Context, in *Image, opts ...grpc.CallOption) (*Empty, error)
	Inpaint(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Image, error)
	UberInpaint(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Image, error)
	Img2Img(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Image, error)
	Txt2Img(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Image, error)
	Ipnet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Image, error)
	Reboot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type comfyClient struct {
	cc grpc.ClientConnInterface
}

func NewComfyClient(cc grpc.ClientConnInterface) ComfyClient {
	return &comfyClient{cc}
}

func (c *comfyClient) SetImage(ctx context.Context, in *SlotedImage, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Comfy_SetImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comfyClient) SetPrompt(ctx context.Context, in *SlotedPrompt, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Comfy_SetPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comfyClient) SetMask(ctx context.Context, in *Image, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Comfy_SetMask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comfyClient) SetOptions(ctx context.Context, in *Options, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Comfy_SetOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comfyClient) SetCrop(ctx context.Context, in *Image, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Comfy_SetCrop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comfyClient) Inpaint(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, Comfy_Inpaint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comfyClient) UberInpaint(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, Comfy_UberInpaint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comfyClient) Img2Img(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, Comfy_Img2Img_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comfyClient) Txt2Img(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, Comfy_Txt2Img_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comfyClient) Ipnet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, Comfy_Ipnet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comfyClient) Reboot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Comfy_Reboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComfyServer is the server API for Comfy service.
// All implementations must embed UnimplementedComfyServer
// for forward compatibility.
type ComfyServer interface {
	SetImage(context.Context, *SlotedImage) (*Empty, error)
	SetPrompt(context.Context, *SlotedPrompt) (*Empty, error)
	SetMask(context.Context, *Image) (*Empty, error)
	SetOptions(context.Context, *Options) (*Empty, error)
	SetCrop(context.Context, *Image) (*Empty, error)
	Inpaint(context.Context, *Empty) (*Image, error)
	UberInpaint(context.Context, *Empty) (*Image, error)
	Img2Img(context.Context, *Empty) (*Image, error)
	Txt2Img(context.Context, *Empty) (*Image, error)
	Ipnet(context.Context, *Empty) (*Image, error)
	Reboot(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedComfyServer()
}

// UnimplementedComfyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComfyServer struct{}

func (UnimplementedComfyServer) SetImage(context.Context, *SlotedImage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetImage not implemented")
}
func (UnimplementedComfyServer) SetPrompt(context.Context, *SlotedPrompt) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPrompt not implemented")
}
func (UnimplementedComfyServer) SetMask(context.Context, *Image) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMask not implemented")
}
func (UnimplementedComfyServer) SetOptions(context.Context, *Options) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetOptions not implemented")
}
func (UnimplementedComfyServer) SetCrop(context.Context, *Image) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCrop not implemented")
}
func (UnimplementedComfyServer) Inpaint(context.Context, *Empty) (*Image, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inpaint not implemented")
}
func (UnimplementedComfyServer) UberInpaint(context.Context, *Empty) (*Image, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UberInpaint not implemented")
}
func (UnimplementedComfyServer) Img2Img(context.Context, *Empty) (*Image, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Img2Img not implemented")
}
func (UnimplementedComfyServer) Txt2Img(context.Context, *Empty) (*Image, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Txt2Img not implemented")
}
func (UnimplementedComfyServer) Ipnet(context.Context, *Empty) (*Image, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ipnet not implemented")
}
func (UnimplementedComfyServer) Reboot(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reboot not implemented")
}
func (UnimplementedComfyServer) mustEmbedUnimplementedComfyServer() {}
func (UnimplementedComfyServer) testEmbeddedByValue()               {}

// UnsafeComfyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComfyServer will
// result in compilation errors.
type UnsafeComfyServer interface {
	mustEmbedUnimplementedComfyServer()
}

func RegisterComfyServer(s grpc.ServiceRegistrar, srv ComfyServer) {
	// If the following call pancis, it indicates UnimplementedComfyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Comfy_ServiceDesc, srv)
}

func _Comfy_SetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotedImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComfyServer).SetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comfy_SetImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComfyServer).SetImage(ctx, req.(*SlotedImage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comfy_SetPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotedPrompt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComfyServer).SetPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comfy_SetPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComfyServer).SetPrompt(ctx, req.(*SlotedPrompt))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comfy_SetMask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Image)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComfyServer).SetMask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comfy_SetMask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComfyServer).SetMask(ctx, req.(*Image))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comfy_SetOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Options)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComfyServer).SetOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comfy_SetOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComfyServer).SetOptions(ctx, req.(*Options))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comfy_SetCrop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Image)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComfyServer).SetCrop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comfy_SetCrop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComfyServer).SetCrop(ctx, req.(*Image))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comfy_Inpaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComfyServer).Inpaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comfy_Inpaint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComfyServer).Inpaint(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comfy_UberInpaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComfyServer).UberInpaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comfy_UberInpaint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComfyServer).UberInpaint(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comfy_Img2Img_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComfyServer).Img2Img(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comfy_Img2Img_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComfyServer).Img2Img(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comfy_Txt2Img_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComfyServer).Txt2Img(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comfy_Txt2Img_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComfyServer).Txt2Img(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comfy_Ipnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComfyServer).Ipnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comfy_Ipnet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComfyServer).Ipnet(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comfy_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComfyServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Comfy_Reboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComfyServer).Reboot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Comfy_ServiceDesc is the grpc.ServiceDesc for Comfy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Comfy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meagen.Comfy",
	HandlerType: (*ComfyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetImage",
			Handler:    _Comfy_SetImage_Handler,
		},
		{
			MethodName: "SetPrompt",
			Handler:    _Comfy_SetPrompt_Handler,
		},
		{
			MethodName: "SetMask",
			Handler:    _Comfy_SetMask_Handler,
		},
		{
			MethodName: "SetOptions",
			Handler:    _Comfy_SetOptions_Handler,
		},
		{
			MethodName: "SetCrop",
			Handler:    _Comfy_SetCrop_Handler,
		},
		{
			MethodName: "Inpaint",
			Handler:    _Comfy_Inpaint_Handler,
		},
		{
			MethodName: "UberInpaint",
			Handler:    _Comfy_UberInpaint_Handler,
		},
		{
			MethodName: "Img2Img",
			Handler:    _Comfy_Img2Img_Handler,
		},
		{
			MethodName: "Txt2Img",
			Handler:    _Comfy_Txt2Img_Handler,
		},
		{
			MethodName: "Ipnet",
			Handler:    _Comfy_Ipnet_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _Comfy_Reboot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/comfy.proto",
}
