// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/comfy.proto

package mea_gen_d

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImgType int32

const (
	ImgType_NONE ImgType = 0
	ImgType_MONO ImgType = 1
	ImgType_DUO  ImgType = 2
	ImgType_RGB  ImgType = 3
	ImgType_RGBA ImgType = 4
)

// Enum value maps for ImgType.
var (
	ImgType_name = map[int32]string{
		0: "NONE",
		1: "MONO",
		2: "DUO",
		3: "RGB",
		4: "RGBA",
	}
	ImgType_value = map[string]int32{
		"NONE": 0,
		"MONO": 1,
		"DUO":  2,
		"RGB":  3,
		"RGBA": 4,
	}
)

func (x ImgType) Enum() *ImgType {
	p := new(ImgType)
	*p = x
	return p
}

func (x ImgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImgType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_comfy_proto_enumTypes[0].Descriptor()
}

func (ImgType) Type() protoreflect.EnumType {
	return &file_api_proto_comfy_proto_enumTypes[0]
}

func (x ImgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImgType.Descriptor instead.
func (ImgType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_comfy_proto_rawDescGZIP(), []int{0}
}

type InpaintType int32

const (
	InpaintType_SDXL InpaintType = 0
	InpaintType_FLUX InpaintType = 1
	InpaintType_BOTH InpaintType = 2
)

// Enum value maps for InpaintType.
var (
	InpaintType_name = map[int32]string{
		0: "SDXL",
		1: "FLUX",
		2: "BOTH",
	}
	InpaintType_value = map[string]int32{
		"SDXL": 0,
		"FLUX": 1,
		"BOTH": 2,
	}
)

func (x InpaintType) Enum() *InpaintType {
	p := new(InpaintType)
	*p = x
	return p
}

func (x InpaintType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InpaintType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_comfy_proto_enumTypes[1].Descriptor()
}

func (InpaintType) Type() protoreflect.EnumType {
	return &file_api_proto_comfy_proto_enumTypes[1]
}

func (x InpaintType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InpaintType.Descriptor instead.
func (InpaintType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_comfy_proto_rawDescGZIP(), []int{1}
}

type Slot int32

const (
	Slot_a Slot = 0
	Slot_b Slot = 1
	Slot_c Slot = 2
)

// Enum value maps for Slot.
var (
	Slot_name = map[int32]string{
		0: "a",
		1: "b",
		2: "c",
	}
	Slot_value = map[string]int32{
		"a": 0,
		"b": 1,
		"c": 2,
	}
)

func (x Slot) Enum() *Slot {
	p := new(Slot)
	*p = x
	return p
}

func (x Slot) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Slot) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_comfy_proto_enumTypes[2].Descriptor()
}

func (Slot) Type() protoreflect.EnumType {
	return &file_api_proto_comfy_proto_enumTypes[2]
}

func (x Slot) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Slot.Descriptor instead.
func (Slot) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_comfy_proto_rawDescGZIP(), []int{2}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_proto_comfy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_comfy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_comfy_proto_rawDescGZIP(), []int{0}
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XPos          uint32                 `protobuf:"varint,1,opt,name=x_pos,json=xPos,proto3" json:"x_pos,omitempty"`
	YPos          uint32                 `protobuf:"varint,2,opt,name=y_pos,json=yPos,proto3" json:"y_pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_proto_comfy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_comfy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_proto_comfy_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetXPos() uint32 {
	if x != nil {
		return x.XPos
	}
	return 0
}

func (x *Position) GetYPos() uint32 {
	if x != nil {
		return x.YPos
	}
	return 0
}

type PatchPixels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pixels        []byte                 `protobuf:"bytes,1,opt,name=pixels,proto3" json:"pixels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchPixels) Reset() {
	*x = PatchPixels{}
	mi := &file_api_proto_comfy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchPixels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchPixels) ProtoMessage() {}

func (x *PatchPixels) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_comfy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchPixels.ProtoReflect.Descriptor instead.
func (*PatchPixels) Descriptor() ([]byte, []int) {
	return file_api_proto_comfy_proto_rawDescGZIP(), []int{2}
}

func (x *PatchPixels) GetPixels() []byte {
	if x != nil {
		return x.Pixels
	}
	return nil
}

type ImgInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	ImgType       ImgType                `protobuf:"varint,3,opt,name=img_type,json=imgType,proto3,enum=meagen.ImgType" json:"img_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImgInfo) Reset() {
	*x = ImgInfo{}
	mi := &file_api_proto_comfy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImgInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgInfo) ProtoMessage() {}

func (x *ImgInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_comfy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgInfo.ProtoReflect.Descriptor instead.
func (*ImgInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_comfy_proto_rawDescGZIP(), []int{3}
}

func (x *ImgInfo) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImgInfo) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImgInfo) GetImgType() ImgType {
	if x != nil {
		return x.ImgType
	}
	return ImgType_NONE
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *ImgInfo               `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Pixels        []byte                 `protobuf:"bytes,2,opt,name=pixels,proto3" json:"pixels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_api_proto_comfy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_comfy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_api_proto_comfy_proto_rawDescGZIP(), []int{4}
}

func (x *Image) GetInfo() *ImgInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Image) GetPixels() []byte {
	if x != nil {
		return x.Pixels
	}
	return nil
}

type InpaintData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Img           *Image                 `protobuf:"bytes,1,opt,name=img,proto3" json:"img,omitempty"`
	Mask          *Image                 `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InpaintData) Reset() {
	*x = InpaintData{}
	mi := &file_api_proto_comfy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InpaintData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InpaintData) ProtoMessage() {}

func (x *InpaintData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_comfy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InpaintData.ProtoReflect.Descriptor instead.
func (*InpaintData) Descriptor() ([]byte, []int) {
	return file_api_proto_comfy_proto_rawDescGZIP(), []int{5}
}

func (x *InpaintData) GetImg() *Image {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *InpaintData) GetMask() *Image {
	if x != nil {
		return x.Mask
	}
	return nil
}

type Options struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          uint32                 `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	ImgPower      float32                `protobuf:"fixed32,2,opt,name=img_power,json=imgPower,proto3" json:"img_power,omitempty"`
	ModelFlag     InpaintType            `protobuf:"varint,3,opt,name=model_flag,json=modelFlag,proto3,enum=meagen.InpaintType" json:"model_flag,omitempty"`
	PromptChain   []Slot                 `protobuf:"varint,4,rep,packed,name=prompt_chain,json=promptChain,proto3,enum=meagen.Slot" json:"prompt_chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_api_proto_comfy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_comfy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_api_proto_comfy_proto_rawDescGZIP(), []int{6}
}

func (x *Options) GetSeed() uint32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *Options) GetImgPower() float32 {
	if x != nil {
		return x.ImgPower
	}
	return 0
}

func (x *Options) GetModelFlag() InpaintType {
	if x != nil {
		return x.ModelFlag
	}
	return InpaintType_SDXL
}

func (x *Options) GetPromptChain() []Slot {
	if x != nil {
		return x.PromptChain
	}
	return nil
}

type SlotedImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          Slot                   `protobuf:"varint,1,opt,name=slot,proto3,enum=meagen.Slot" json:"slot,omitempty"`
	Image         *Image                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotedImage) Reset() {
	*x = SlotedImage{}
	mi := &file_api_proto_comfy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotedImage) ProtoMessage() {}

func (x *SlotedImage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_comfy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotedImage.ProtoReflect.Descriptor instead.
func (*SlotedImage) Descriptor() ([]byte, []int) {
	return file_api_proto_comfy_proto_rawDescGZIP(), []int{7}
}

func (x *SlotedImage) GetSlot() Slot {
	if x != nil {
		return x.Slot
	}
	return Slot_a
}

func (x *SlotedImage) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type SlotedPrompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          Slot                   `protobuf:"varint,1,opt,name=slot,proto3,enum=meagen.Slot" json:"slot,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotedPrompt) Reset() {
	*x = SlotedPrompt{}
	mi := &file_api_proto_comfy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotedPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotedPrompt) ProtoMessage() {}

func (x *SlotedPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_comfy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotedPrompt.ProtoReflect.Descriptor instead.
func (*SlotedPrompt) Descriptor() ([]byte, []int) {
	return file_api_proto_comfy_proto_rawDescGZIP(), []int{8}
}

func (x *SlotedPrompt) GetSlot() Slot {
	if x != nil {
		return x.Slot
	}
	return Slot_a
}

func (x *SlotedPrompt) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

var File_api_proto_comfy_proto protoreflect.FileDescriptor

const file_api_proto_comfy_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/comfy.proto\x12\x06meagen\"\a\n" +
	"\x05Empty\"4\n" +
	"\bPosition\x12\x13\n" +
	"\x05x_pos\x18\x01 \x01(\rR\x04xPos\x12\x13\n" +
	"\x05y_pos\x18\x02 \x01(\rR\x04yPos\"%\n" +
	"\vPatchPixels\x12\x16\n" +
	"\x06pixels\x18\x01 \x01(\fR\x06pixels\"c\n" +
	"\aImgInfo\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12*\n" +
	"\bimg_type\x18\x03 \x01(\x0e2\x0f.meagen.ImgTypeR\aimgType\"D\n" +
	"\x05Image\x12#\n" +
	"\x04info\x18\x01 \x01(\v2\x0f.meagen.ImgInfoR\x04info\x12\x16\n" +
	"\x06pixels\x18\x02 \x01(\fR\x06pixels\"Q\n" +
	"\vInpaintData\x12\x1f\n" +
	"\x03img\x18\x01 \x01(\v2\r.meagen.ImageR\x03img\x12!\n" +
	"\x04mask\x18\x02 \x01(\v2\r.meagen.ImageR\x04mask\"\x9f\x01\n" +
	"\aOptions\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\rR\x04seed\x12\x1b\n" +
	"\timg_power\x18\x02 \x01(\x02R\bimgPower\x122\n" +
	"\n" +
	"model_flag\x18\x03 \x01(\x0e2\x13.meagen.InpaintTypeR\tmodelFlag\x12/\n" +
	"\fprompt_chain\x18\x04 \x03(\x0e2\f.meagen.SlotR\vpromptChain\"T\n" +
	"\vSlotedImage\x12 \n" +
	"\x04slot\x18\x01 \x01(\x0e2\f.meagen.SlotR\x04slot\x12#\n" +
	"\x05image\x18\x02 \x01(\v2\r.meagen.ImageR\x05image\"H\n" +
	"\fSlotedPrompt\x12 \n" +
	"\x04slot\x18\x01 \x01(\x0e2\f.meagen.SlotR\x04slot\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt*9\n" +
	"\aImgType\x12\b\n" +
	"\x04NONE\x10\x00\x12\b\n" +
	"\x04MONO\x10\x01\x12\a\n" +
	"\x03DUO\x10\x02\x12\a\n" +
	"\x03RGB\x10\x03\x12\b\n" +
	"\x04RGBA\x10\x04*+\n" +
	"\vInpaintType\x12\b\n" +
	"\x04SDXL\x10\x00\x12\b\n" +
	"\x04FLUX\x10\x01\x12\b\n" +
	"\x04BOTH\x10\x02*\x1b\n" +
	"\x04Slot\x12\x05\n" +
	"\x01a\x10\x00\x12\x05\n" +
	"\x01b\x10\x01\x12\x05\n" +
	"\x01c\x10\x022\xf6\x03\n" +
	"\x05Comfy\x120\n" +
	"\bSetImage\x12\x13.meagen.SlotedImage\x1a\r.meagen.Empty\"\x00\x122\n" +
	"\tSetPrompt\x12\x14.meagen.SlotedPrompt\x1a\r.meagen.Empty\"\x00\x12)\n" +
	"\aSetMask\x12\r.meagen.Image\x1a\r.meagen.Empty\"\x00\x12.\n" +
	"\n" +
	"SetOptions\x12\x0f.meagen.Options\x1a\r.meagen.Empty\"\x00\x12)\n" +
	"\aSetCrop\x12\r.meagen.Image\x1a\r.meagen.Empty\"\x00\x12)\n" +
	"\aInpaint\x12\r.meagen.Empty\x1a\r.meagen.Image\"\x00\x12-\n" +
	"\vUberInpaint\x12\r.meagen.Empty\x1a\r.meagen.Image\"\x00\x12)\n" +
	"\aImg2Img\x12\r.meagen.Empty\x1a\r.meagen.Image\"\x00\x12)\n" +
	"\aTxt2Img\x12\r.meagen.Empty\x1a\r.meagen.Image\"\x00\x12'\n" +
	"\x05Ipnet\x12\r.meagen.Empty\x1a\r.meagen.Image\"\x00\x12(\n" +
	"\x06Reboot\x12\r.meagen.Empty\x1a\r.meagen.Empty\"\x00B\fZ\n" +
	"mea.gen.d/b\x06proto3"

var (
	file_api_proto_comfy_proto_rawDescOnce sync.Once
	file_api_proto_comfy_proto_rawDescData []byte
)

func file_api_proto_comfy_proto_rawDescGZIP() []byte {
	file_api_proto_comfy_proto_rawDescOnce.Do(func() {
		file_api_proto_comfy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_comfy_proto_rawDesc), len(file_api_proto_comfy_proto_rawDesc)))
	})
	return file_api_proto_comfy_proto_rawDescData
}

var file_api_proto_comfy_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_comfy_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_comfy_proto_goTypes = []any{
	(ImgType)(0),         // 0: meagen.ImgType
	(InpaintType)(0),     // 1: meagen.InpaintType
	(Slot)(0),            // 2: meagen.Slot
	(*Empty)(nil),        // 3: meagen.Empty
	(*Position)(nil),     // 4: meagen.Position
	(*PatchPixels)(nil),  // 5: meagen.PatchPixels
	(*ImgInfo)(nil),      // 6: meagen.ImgInfo
	(*Image)(nil),        // 7: meagen.Image
	(*InpaintData)(nil),  // 8: meagen.InpaintData
	(*Options)(nil),      // 9: meagen.Options
	(*SlotedImage)(nil),  // 10: meagen.SlotedImage
	(*SlotedPrompt)(nil), // 11: meagen.SlotedPrompt
}
var file_api_proto_comfy_proto_depIdxs = []int32{
	0,  // 0: meagen.ImgInfo.img_type:type_name -> meagen.ImgType
	6,  // 1: meagen.Image.info:type_name -> meagen.ImgInfo
	7,  // 2: meagen.InpaintData.img:type_name -> meagen.Image
	7,  // 3: meagen.InpaintData.mask:type_name -> meagen.Image
	1,  // 4: meagen.Options.model_flag:type_name -> meagen.InpaintType
	2,  // 5: meagen.Options.prompt_chain:type_name -> meagen.Slot
	2,  // 6: meagen.SlotedImage.slot:type_name -> meagen.Slot
	7,  // 7: meagen.SlotedImage.image:type_name -> meagen.Image
	2,  // 8: meagen.SlotedPrompt.slot:type_name -> meagen.Slot
	10, // 9: meagen.Comfy.SetImage:input_type -> meagen.SlotedImage
	11, // 10: meagen.Comfy.SetPrompt:input_type -> meagen.SlotedPrompt
	7,  // 11: meagen.Comfy.SetMask:input_type -> meagen.Image
	9,  // 12: meagen.Comfy.SetOptions:input_type -> meagen.Options
	7,  // 13: meagen.Comfy.SetCrop:input_type -> meagen.Image
	3,  // 14: meagen.Comfy.Inpaint:input_type -> meagen.Empty
	3,  // 15: meagen.Comfy.UberInpaint:input_type -> meagen.Empty
	3,  // 16: meagen.Comfy.Img2Img:input_type -> meagen.Empty
	3,  // 17: meagen.Comfy.Txt2Img:input_type -> meagen.Empty
	3,  // 18: meagen.Comfy.Ipnet:input_type -> meagen.Empty
	3,  // 19: meagen.Comfy.Reboot:input_type -> meagen.Empty
	3,  // 20: meagen.Comfy.SetImage:output_type -> meagen.Empty
	3,  // 21: meagen.Comfy.SetPrompt:output_type -> meagen.Empty
	3,  // 22: meagen.Comfy.SetMask:output_type -> meagen.Empty
	3,  // 23: meagen.Comfy.SetOptions:output_type -> meagen.Empty
	3,  // 24: meagen.Comfy.SetCrop:output_type -> meagen.Empty
	7,  // 25: meagen.Comfy.Inpaint:output_type -> meagen.Image
	7,  // 26: meagen.Comfy.UberInpaint:output_type -> meagen.Image
	7,  // 27: meagen.Comfy.Img2Img:output_type -> meagen.Image
	7,  // 28: meagen.Comfy.Txt2Img:output_type -> meagen.Image
	7,  // 29: meagen.Comfy.Ipnet:output_type -> meagen.Image
	3,  // 30: meagen.Comfy.Reboot:output_type -> meagen.Empty
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_comfy_proto_init() }
func file_api_proto_comfy_proto_init() {
	if File_api_proto_comfy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_comfy_proto_rawDesc), len(file_api_proto_comfy_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_comfy_proto_goTypes,
		DependencyIndexes: file_api_proto_comfy_proto_depIdxs,
		EnumInfos:         file_api_proto_comfy_proto_enumTypes,
		MessageInfos:      file_api_proto_comfy_proto_msgTypes,
	}.Build()
	File_api_proto_comfy_proto = out.File
	file_api_proto_comfy_proto_goTypes = nil
	file_api_proto_comfy_proto_depIdxs = nil
}
