// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/proto/llm.proto

package mea_gen_d

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_system    Role = 0
	Role_user      Role = 1
	Role_assistant Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "system",
		1: "user",
		2: "assistant",
	}
	Role_value = map[string]int32{
		"system":    0,
		"user":      1,
		"assistant": 2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_llm_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_api_proto_llm_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_llm_proto_rawDescGZIP(), []int{0}
}

type ChatResoponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResoponse) Reset() {
	*x = ChatResoponse{}
	mi := &file_api_proto_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResoponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResoponse) ProtoMessage() {}

func (x *ChatResoponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResoponse.ProtoReflect.Descriptor instead.
func (*ChatResoponse) Descriptor() ([]byte, []int) {
	return file_api_proto_llm_proto_rawDescGZIP(), []int{0}
}

func (x *ChatResoponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// meaby some id
	Role          Role   `protobuf:"varint,1,opt,name=role,proto3,enum=meagen.Role" json:"role,omitempty"`
	Tokens        string `protobuf:"bytes,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proto_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_llm_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_system
}

func (x *Message) GetTokens() string {
	if x != nil {
		return x.Tokens
	}
	return ""
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_api_proto_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_api_proto_llm_proto_rawDescGZIP(), []int{2}
}

func (x *Chat) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_api_proto_llm_proto protoreflect.FileDescriptor

const file_api_proto_llm_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/llm.proto\x12\x06meagen\"#\n" +
	"\rchatResoponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"C\n" +
	"\aMessage\x12 \n" +
	"\x04role\x18\x01 \x01(\x0e2\f.meagen.RoleR\x04role\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\tR\x06tokens\"3\n" +
	"\x04Chat\x12+\n" +
	"\bmessages\x18\x01 \x03(\v2\x0f.meagen.MessageR\bmessages*+\n" +
	"\x04Role\x12\n" +
	"\n" +
	"\x06system\x10\x00\x12\b\n" +
	"\x04user\x10\x01\x12\r\n" +
	"\tassistant\x10\x02B\fZ\n" +
	"mea.gen.d/b\x06proto3"

var (
	file_api_proto_llm_proto_rawDescOnce sync.Once
	file_api_proto_llm_proto_rawDescData []byte
)

func file_api_proto_llm_proto_rawDescGZIP() []byte {
	file_api_proto_llm_proto_rawDescOnce.Do(func() {
		file_api_proto_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_llm_proto_rawDesc), len(file_api_proto_llm_proto_rawDesc)))
	})
	return file_api_proto_llm_proto_rawDescData
}

var file_api_proto_llm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_llm_proto_goTypes = []any{
	(Role)(0),             // 0: meagen.Role
	(*ChatResoponse)(nil), // 1: meagen.chatResoponse
	(*Message)(nil),       // 2: meagen.Message
	(*Chat)(nil),          // 3: meagen.Chat
}
var file_api_proto_llm_proto_depIdxs = []int32{
	0, // 0: meagen.Message.role:type_name -> meagen.Role
	2, // 1: meagen.Chat.messages:type_name -> meagen.Message
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_llm_proto_init() }
func file_api_proto_llm_proto_init() {
	if File_api_proto_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_llm_proto_rawDesc), len(file_api_proto_llm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_llm_proto_goTypes,
		DependencyIndexes: file_api_proto_llm_proto_depIdxs,
		EnumInfos:         file_api_proto_llm_proto_enumTypes,
		MessageInfos:      file_api_proto_llm_proto_msgTypes,
	}.Build()
	File_api_proto_llm_proto = out.File
	file_api_proto_llm_proto_goTypes = nil
	file_api_proto_llm_proto_depIdxs = nil
}
