
self: |
  Jako eksplorator ekserymetalnego agentycznego podejścia historyjkowego. 
  Chciałbym eksplorować behavior agentów wykorzystujących jako core systemy języka ludzkiego.

self_to_self:
  - Czy ja mogę się teraz pytać bezpośednio sam siebie aby poprawić swoje zrozumienie tego tym czym jestem?